import { provideNzIcons } from 'ng-zorro-antd/icon';
import {
  // Layout & Navigation
  DashboardOutline,
  MenuOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  HomeOutline,
  ApartmentOutline,
  // People
  TeamOutline,
  UserOutline,
  UserAddOutline,
  ReloadOutline,
  // Finance
  DollarOutline,
  MoneyCollectOutline,
  WalletOutline,
  RiseOutline,
  FundViewOutline,
  // Documents
  FileTextOutline,
  FileDoneOutline,
  // Utility
  ThunderboltOutline,
  ToolOutline,
  SettingOutline,
  // Actions
  PlusOutline,
  SearchOutline,
  LogoutOutline,
  RightOutline,
  ArrowRightOutline,
  LeftOutline,
  DownOutline,
  // Status
  CheckCircleOutline,
  ExclamationCircleOutline,
  AlertOutline,
  BellOutline,
  NotificationOutline,
  QuestionCircleOutline,
  // Theme
  SunOutline,
  MoonOutline,
  // Bank & Property
  BankOutline,
  ShopOutline,

  EnvironmentOutline,
  CopyOutline,
  LockOutline,
  MailOutline,
  CalendarOutline,
  DeleteOutline,
  EllipsisOutline,
  KeyOutline,
  MessageOutline,
} from '@ant-design/icons-angular/icons';

export const APP_ICONS = [
  DashboardOutline,
  MenuOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  HomeOutline,
  ApartmentOutline,
  TeamOutline,
  UserOutline,
  UserAddOutline,
  DollarOutline,
  MoneyCollectOutline,
  WalletOutline,
  RiseOutline,
  FileTextOutline,
  FileDoneOutline,
  ThunderboltOutline,
  ToolOutline,
  SettingOutline,
  PlusOutline,
  SearchOutline,
  LogoutOutline,
  RightOutline,
  ArrowRightOutline,
  LeftOutline,
  DownOutline,
  CheckCircleOutline,
  ExclamationCircleOutline,
  AlertOutline,
  BellOutline,
  NotificationOutline,
  QuestionCircleOutline,
  SunOutline,
  MoonOutline,
  BankOutline,
  ShopOutline,
  FundViewOutline,
  EnvironmentOutline,
  ReloadOutline,
  CopyOutline,
  LockOutline,
  MailOutline,
  CalendarOutline,
  DeleteOutline,
  EllipsisOutline,
  KeyOutline,
  MessageOutline,
];

export const provideAppIcons = () => provideNzIcons(APP_ICONS);
